version: '3.4'

services:
  patient_db:
    image: mcr.microsoft.com/mssql/server
    
  person_api:
    image: ${DOCKER_REGISTRY-}patientapi
    build:
      context: .
      dockerfile: patient_api/Dockerfile
