version: '3.4'

services:

  persondb:
    container_name: patientdb 
    ports:
    - "1434:1433"
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
  person_api:
    container_name: patient_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__PatientConnectionString=Server=patientdb;Database=patientDb;User Id=sa;Password=SwN12345678"
    ports:
      - "80"
